#pragma once

void RunNavigationRuntimeTests();
void RunSelectionPolicyTests();
void RunActionPolicyTests();
void RunMapSessionStateTests();
void RunCruiseRuntimeTests();
void RunEffectDispatcherTests();
void RunBodyResolverTests();
void RunCruiseControllerTests();
void RunActionPresenterTests();
void RunBodyCatalogTests();
void RunCatalogBodyResolutionSourceTests();
void RunPluginFormIdTests();
void RunSubrecordReaderTests();
void RunRecordBodyDecoderTests();
void RunPlanetDataParserTests();
void RunPluginMasterParserTests();
void RunPluginResolverBuilderTests();
void RunPluginEntryReaderTests();
void RunPluginPlanetScannerTests();
